version: '3.8'

services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unn-hostel-admin
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.local
    volumes:
      - ./logs:/app/logs
      - ./public:/app/public
    networks:
      - app-network
    depends_on:
      - nginx

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: unn-hostel-admin-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - app

  # PM2 Process Manager (Optional)
  pm2:
    image: node:18-alpine
    container_name: unn-hostel-admin-pm2
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npm install -g pm2 &&
             yarn install --frozen-lockfile &&
             yarn build &&
             pm2 start ecosystem.config.js &&
             pm2 logs"
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  app-logs:
    driver: local
