import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { HelpCircle, Search, MessageSquare, Phone, Mail, BookOpen, Video, FileText, ChevronDown, ChevronRight, ExternalLink } from 'lucide-react'
import StudentHeader from '@/components/layout/student-header'
import { QuickActions } from '@/components/ui/quick-actions' 